version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  scraper:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:80"
    # RUN_ON_STARTUP environment değişkeni ile scraper başlatılır başlatılmaz hemen çalışır.
    # Kullanmak için aşağıdaki satırın başındaki # işaretini kaldırın veya terminalden -e RUN_ON_STARTUP=true ile çalıştırın.
    # - RUN_ON_STARTUP=true
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/case_study
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # - RUN_ON_STARTUP=true
    restart: on-failure
