version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  scraper:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/case_study
    restart: on-failure
