services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study  # You can change those
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  scraper:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app  # Remove 'cached' for simpler volume binding
    environment:
      DB_URL: postgresql://user:password@postgres:5432/case_study  # Doğru bağlantı URL'si
    restart: always  # Ensure the container restarts automatically
