name: Scraper Cron Job

on:
  schedule:
    # Run the scraper every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t case_study .

      # Step 3: Run the scraper inside Docker
      - name: Run scraper
        run: |
          docker run --rm case_study
