name: Scraper Cron Job


# Database already initialized. Skipping table creation.
# Total campgrounds available in API: 500
# 1. --- Processing campground: Hocking Hills State Park ---
# Step 1: Validating raw data...
# Step 2: Validation successful.
# Step 3: Saving to the database...
# Step 4: Campground does not exist. Adding new record...
# Step 5: New campground successfully added: Hocking Hills State Park
# ...
# All campgrounds have been processed.
# Processed 500 out of 500 campgrounds.

on:
  schedule:
    # Run the scraper every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t case_study .

      # Step 3: Run the scraper inside Docker
      - name: Run scraper
        run: |
          docker run --rm case_study
